name: wonder_kids
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+14

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.3
  audioplayers: ^6.5.1
  provider: ^6.1.5+1
  flip_card: ^0.7.0
  confetti: ^0.8.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1  # <--- thêm plugin sinh icon

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"   # <--- logo gốc (1024x1024)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/config/letters.json
    - assets/images/letters/
    - assets/audio/letters/
    - assets/audio/ting.mp3
    - assets/audio/correct.mp3
    - assets/audio/wrong.mp3
    - assets/images/icon_book.png
    - assets/images/icon_flashcard.png
    - assets/images/icon_game.png
    - assets/audio/bgm.mp3
    - assets/audio/pop.mp3
    - assets/images/cloud.png
    - assets/audio/star.mp3
    - assets/audio/crown.mp3
    - assets/audio/voice_correct.mp3
    - assets/audio/voice_wrong.mp3
    - assets/images/game/
    - assets/images/mascot/
    - assets/audio/
